// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzxnxqxazlttuxxhhhnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eG54cXhhemx0dHV4eGhoaG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNDk1ODksImV4cCI6MjA3NTkyNTU4OX0.aCzlVX7NliWpfLHA_oUX4XEzUr-ip6i8ypHWuFN48XU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});